### PR TITLE
Fix standalone dynadv driver

### LINKED ISSUE #21: Standalone FV3+ADV core driver is broken
There is a standalone driver for the FV3+ADV core option. This runs both the DynCoreGridComp and the AdvCoreGridcomp. WIth the latest changes the non-moist tracers can be advected by the AdvCoreGridComp. The driver is currently broken when trying to run it for various reasons.

### PR DESCRIPTION
**Pull request by bena-nasa**
Fixes #21 

This fixes issue 21 that the standalone dynadv core driver was broken. The driver's main grid comp was trying to add the fields in the tradv bundle from dyncore into the tradv bundle in the advcore. Apparently this is no longer necessary as somehow thru the magic of mapl the fact that dyncore has populated the tradv bundle means that advcore's tradv bundle has also been filled, must be sharing pointers underneath. 

In addition to look at the advected tracers it was necessary to add code.  The tradv bundle is not exported. In standalone mode an export bundle tradvex is created and the fields in tradv are copied to this bundle. Just copying the fields in the tradv bundle to tradvex that history can use is not enough. They need extra decoration that the mapl field creation normally performs. With these changes the fields can be pulled out of the bundle and output in History.

### CODE REVIEW

File: StandAlone_DynAdvCore_GridCompMod.F90 [hunk 1]
```diff
@@ -85,9 +85,8 @@ subroutine SetServices(GC, rc)
       call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_FINALIZE,    Finalize,   RC=status )
       VERIFY_(STATUS)
 
-      ! Create childrens gridded components and invoke their SetServices
+      ! Creat childrens gridded components and invoke their SetServices
```
Comment (mathomp4) [inline StandAlone_DynAdvCore_GridCompMod.F90]: Uh oh. Misspelling crept in.

**Comment by tclune** [comment]
If someone does fix the spelling, probably should put an apostrophe at the end of "childrens" as well.
